apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boundary-worker.name" . }}-config
  labels:
    {{- include "boundary-worker.labels" . | nindent 4 }}
data:
  config.hcl: |

    disable_mlock = true

    listener "tcp" {
        purpose = "proxy"
        tls_disable = {{ .Values.config.tlsDisable | default "true"}}
        address = "0.0.0.0"
    }

    worker {
      name = "{{ include "boundary-worker.name" . }}"
      description = "{{ .Values.config.description | default "A worker for Boundary"}}"

      controllers = ["{{ .Values.config.controller.ips }}"]

      public_addr = "{{ .Values.config.hostname }}:80"
    }

    kms "gcpckms" {
      purpose     = "worker-auth"
      project     = "{{ .Values.config.kms.gcp.project }}"
      region      = "{{ .Values.config.kms.gcp.region | default "global" }}"
      key_ring    = "{{ .Values.config.kms.gcp.keyRing }}"
      crypto_key  = "{{ .Values.config.kms.gcp.key }}"
    }
