apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: boundary-credentials
spec:
  backendType: gcpSecretsManager
  projectId: padok-playground
  data:
    - key: boundary-pg-user
      name: MIGRATION_PG_URL
      version: 1
    - key: boundary-pg-user
      name: BOUNDARY_PG_URL
      version: 1
