apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "boundary-controller.name" . }}-config
  labels:
    {{- include "boundary-controller.labels" . | nindent 4 }}
data:
  config.hcl: |

    disable_mlock = true

    controller {
      name = "{{ include "boundary-controller.name" . }}"
      description = "{{ .Values.config.description | default "A controller for Boundary"}}"
      public_cluster_addr = "35.233.63.90:80"
      database {
          url = "env://{{ .Values.config.db.standardEnvironmentVariable | default "BOUNDARY_PG_URL" }}"
          migration_url = "env://{{ .Values.config.db.migrationEnvironmentVariable | default "MIGRATION_PG_URL" }}"
          max_open_connections = {{ .Values.config.db.maxOpenConnections }}
      }
    }

    listener "tcp" {
      address = "0.0.0.0"
      purpose = "api"

      tls_disable = {{ .Values.config.api.tlsDisable }}
      cors_enabled = true
      cors_allowed_origins = ["*"]
    }

    listener "tcp" {
      address = "0.0.0.0"
      purpose = "cluster"
    }

    kms "gcpckms" {
      purpose     = "root"
      project     = "{{ .Values.config.kms.root.gcp.project }}"
      region      = "{{ .Values.config.kms.root.gcp.region | default "global" }}"
      key_ring    = "{{ .Values.config.kms.root.gcp.keyRing }}"
      crypto_key  = "{{ .Values.config.kms.root.gcp.key }}"
    }

    kms "gcpckms" {
      purpose     = "worker-auth"
      project     = "{{ .Values.config.kms.worker.gcp.project }}"
      region      = "{{ .Values.config.kms.worker.gcp.region | default "global" }}"
      key_ring    = "{{ .Values.config.kms.worker.gcp.keyRing }}"
      crypto_key  = "{{ .Values.config.kms.worker.gcp.key }}"
    }

    kms "gcpckms" {
      purpose     = "recovery"
      project     = "{{ .Values.config.kms.recovery.gcp.project }}"
      region      = "{{ .Values.config.kms.recovery.gcp.region | default "global" }}"
      key_ring    = "{{ .Values.config.kms.recovery.gcp.keyRing }}"
      crypto_key  = "{{ .Values.config.kms.recovery.gcp.key }}"
    }
